CREATE TABLE Users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(20) NOT NULL,
  email VARCHAR(50) NOT NULL
);

CREATE TABLE Author (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(20) NOT NULL
);

CREATE TABLE Books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(50) NOT NULL,
  author_id INTEGER NOT NULL,
  availability INTEGER DEFAULT 1,
  FOREIGN KEY (author_id) REFERENCES Author (id)
);

CREATE TABLE Booking (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  book_id INTEGER NOT NULL,
  booking_date DATE DEFAULT CURRENT_DATE,
  FOREIGN KEY (user_id) REFERENCES Users (id),
  FOREIGN KEY (book_id) REFERENCES Books (id)
);