CREATE TABLE Users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT False
);

CREATE TABLE Authors (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL
);

CREATE TABLE Books (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  author_id INTEGER NOT NULL,
  max_booking_time INTEGER NOT NULL,
  availability INTEGER DEFAULT 1,
  FOREIGN KEY (author_id) REFERENCES Authors (id)
);

CREATE TABLE Booking (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  book_id INTEGER NOT NULL,
  booking_date DATE DEFAULT CURRENT_DATE,
  FOREIGN KEY (user_id) REFERENCES Users (id),
  FOREIGN KEY (book_id) REFERENCES Books (id)
);

CREATE TABLE Genres (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(20)
);

CREATE TABLE Preferences (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  genre_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Users (id),
  FOREIGN KEY (genre_id) REFERENCES Genres (id)
);